config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :crypto
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crypto_controller.rb
class CryptoController < ApplicationController
  def create
    @crypto = Crypto.find(params[:crypto])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    StartScrap.new.perform
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/crypto/create.html.erb
<p>Cryptomonnaie choisie : <%= @crypto.name %></p>
<br>
<p> Valeur : <%= @crypto.value %></p>

app/views/home/index.html.erb
<%= form_tag( crypto_index_path, method: :post) do |f| %>
<%= select_tag "crypto", options_from_collection_for_select(Crypto.all, "id", "name") %>
<%= submit_tag 'Go' %>
<% end %>

<p>Choisis une crypto pour connaître son cours</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsScrapper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>